### ISSUE TITLE
PDF (multcomp package)

### ISSUE THREAD

**Issue by AndrewKinsman** [MangoTheCat/making-r-go-faster-workshop#1]
Hi Graham,

Looking forward to your LondonR workshop next week. 

One small thing I noticed while browsing the materials. On page 2-5 of the PDF you state: "With the **multicomp** package installed...". I believe that this should read "With the **multcomp** package installed..."

Best regards,
Andrew

**Comment by grahamrp** [comment]
Good spot, thanks!
