### ISSUE TITLE
PDF (allHashes)

### ISSUE THREAD

**Issue by AndrewKinsman** [MangoTheCat/making-r-go-faster-workshop#2]
One more small issue. On page 4-3 it says:

library(digest)
hashedPIN <- "600272d88d7961888d606497e8380280c2e95314"
findPIN <- function(hashedPIN) {
potentialPINs <- formatC(seq.int(0,99999), width = 5,format = "d", flag= "0")
allHashes <- lapply(potentialPINs, FUN = sha1)
allHashes <- unlist(allHashes)
names(allHashes) <- allHashes
return(names(**allPINs**[which(**allPINs** == hashedPIN)]))
}

There's no allPINS, so presumably the last line of the code should read:
return(names(**allHashes**[which(**allHashes** == hashedPIN)]))

Of course, the exact same issue arises with the parallel version of this function on page 4-4.

Incidentally, there's also a tiny typo on that same page:
"As **mentione** above..." should be "**As mentioned** above..."

and another one on page 4-5:
"...with each session **communicteing** via sockets." should be "...with each session **communicating** via sockets."

This a really excellent tutorial, thanks Graham.

**Comment by grahamrp** [comment]
Oops, thanks!
